
-- Generated by Gemini at 2025-12-09

-- =================================================================
-- 1. Table Creation
-- =================================================================

-- Universidad Table
-- Purpose: Stores university information.
CREATE TABLE IF NOT EXISTS universidad (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    dominio TEXT[],
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE universidad IS 'Stores university information, including name and email domains.';

-- Carrera Table
-- Purpose: Stores career information for each university.
CREATE TABLE IF NOT EXISTS carrera (
    id SERIAL PRIMARY KEY,
    id_universidad INTEGER NOT NULL REFERENCES universidad(id) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE carrera IS 'Stores academic careers associated with each university.';

-- Usuario Table
-- Purpose: Stores user profile information.
CREATE TABLE IF NOT EXISTS usuario (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    correo VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) UNIQUE,
    rol VARCHAR(20) DEFAULT 'USER',
    activo BOOLEAN DEFAULT true,
    verificado BOOLEAN DEFAULT false,
    id_universidad INTEGER REFERENCES universidad(id) ON DELETE SET NULL,
    id_carrera INTEGER REFERENCES carrera(id) ON DELETE SET NULL,
    codigo_universitario VARCHAR(50),
    tipo_usuario VARCHAR(50),
    es_agente_externo BOOLEAN DEFAULT false,
    referral_count INTEGER DEFAULT 0,
    calificacion_promedio DECIMAL(3,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE usuario IS 'Main table for user accounts and profile data.';

-- Viaje Table
-- Purpose: Stores trip information created by drivers.
CREATE TABLE IF NOT EXISTS viaje (
    id SERIAL PRIMARY KEY,
    id_conductor INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    origen VARCHAR(255) NOT NULL,
    destino VARCHAR(255) NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    asientos_totales INTEGER NOT NULL,
    asientos_disponibles INTEGER NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    estado VARCHAR(20) DEFAULT 'DISPONIBLE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE viaje IS 'Stores all trips created by drivers.';

-- Reserva Table
-- Purpose: Stores passenger reservations for trips.
CREATE TABLE IF NOT EXISTS reserva (
    id SERIAL PRIMARY KEY,
    id_viaje INTEGER NOT NULL REFERENCES viaje(id) ON DELETE CASCADE,
    id_pasajero INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    asientos INTEGER NOT NULL,
    precio_total DECIMAL(10,2) NOT NULL,
    estado VARCHAR(20) DEFAULT 'PENDIENTE',
    fecha_reserva TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE reserva IS 'Connects users (passengers) to trips they have reserved.';

-- Wallet Table
-- Purpose: Manages user balances.
CREATE TABLE IF NOT EXISTS wallet (
    id SERIAL PRIMARY KEY,
    id_usuario INTEGER NOT NULL UNIQUE REFERENCES usuario(id) ON DELETE CASCADE,
    saldo DECIMAL(10,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE wallet IS 'Stores the financial balance for each user.';

-- Transaccion Table
-- Purpose: Logs all financial transactions.
CREATE TABLE IF NOT EXISTS transaccion (
    id SERIAL PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    tipo VARCHAR(50) NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    descripcion TEXT,
    metodo_pago VARCHAR(50),
    fecha_transaccion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE transaccion IS 'A log of all financial movements (payments, earnings, etc.).';

-- Mensaje_Comunidad Table
-- Purpose: Stores messages for the university community boards.
CREATE TABLE IF NOT EXISTS mensaje_comunidad (
    id SERIAL PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    id_universidad INTEGER NOT NULL REFERENCES universidad(id) ON DELETE CASCADE,
    mensaje TEXT NOT NULL,
    fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE mensaje_comunidad IS 'Stores messages for the university-specific community forums.';

-- =================================================================
-- 2. Seed Data (Universities and Careers)
-- =================================================================

-- Clear existing data to prevent duplicates on re-run
TRUNCATE universidad, carrera RESTART IDENTITY CASCADE;

-- Insert Universities
INSERT INTO universidad (id, nombre, dominio) VALUES
(1, 'Universidad de Piura (UDEP)', ARRAY['udep.edu.pe']),
(2, 'Universidad Nacional de Piura (UNP)', ARRAY['unp.edu.pe', 'alumnos.unp.edu.pe']),
(3, 'Universidad César Vallejo (UCV)', ARRAY['ucv.edu.pe', 'ucvvirtual.edu.pe']),
(4, 'Universidad Privada del Norte (UPN)', ARRAY['upn.edu.pe']),
(5, 'Universidad de San Martín de Porres (USMP)', ARRAY['usmp.pe']),
(6, 'Universidad Tecnológica del Perú (UTP)', ARRAY['utp.edu.pe']);

-- Insert Careers for UDEP (id: 1)
INSERT INTO carrera (id_universidad, nombre) VALUES
(1, 'Administración de Empresas'), (1, 'Administración y Servicios'), (1, 'Arquitectura'),
(1, 'Contabilidad y Auditoría'), (1, 'Derecho'), (1, 'Economía'),
(1, 'Educación Inicial'), (1, 'Educación Primaria'), (1, 'Educación Secundaria (Lengua Inglesa)'),
(1, 'Educación Secundaria (Matemática y Física)'), (1, 'Educación Secundaria (Lengua y Literatura)'),
(1, 'Educación Secundaria (Historia y Ciencias Sociales)'), (1, 'Historia y Gestión Cultural'),
(1, 'Comunicación Audiovisual'), (1, 'Comunicaciones de Marketing'), (1, 'Periodismo'),
(1, 'Ingeniería Civil'), (1, 'Ingeniería Industrial y de Sistemas'), (1, 'Ingeniería Mecánico-Eléctrica');

-- Insert Careers for UNP (id: 2)
INSERT INTO carrera (id_universidad, nombre) VALUES
(2, 'Administración'), (2, 'Contabilidad y Finanzas'), (2, 'Economía'),
(2, 'Estadística'), (2, 'Agronomía'), (2, 'Arquitectura y Urbanismo'),
(2, 'Ingeniería Agrícola'), (2, 'Ingeniería Agroindustrial'), (2, 'Ingeniería Agrónoma'),
(2, 'Ingeniería Ambiental'), (2, 'Ingeniería Civil'), (2, 'Ingeniería Electrónica y Telecomunicaciones'),
(2, 'Ingeniería Geológica'), (2, 'Ingeniería Industrial'), (2, 'Ingeniería Informática'),
(2, 'Ingeniería Mecatrónica'), (2, 'Ingeniería Pesquera'), (2, 'Ingeniería Química'),
(2, 'Ingeniería Zootécnica'), (2, 'Ingeniería de Minas'), (2, 'Ingeniería de Petróleo'),
(2, 'Ciencias Biológicas'), (2, 'Enfermería'), (2, 'Medicina Humana'),
(2, 'Medicina Veterinaria'), (2, 'Psicología'), (2, 'Obstetricia'),
(2, 'Estomatología'), (2, 'Historia y Geografía'), (2, 'Lengua y Literatura'),
(2, 'Educación Inicial'), (2, 'Educación Primaria'), (2, 'Ciencias de la Comunicación'),
(2, 'Derecho y Ciencias Políticas'), (2, 'Matemática'), (2, 'Física');

-- Insert Careers for UCV (id: 3)
INSERT INTO carrera (id_universidad, nombre) VALUES
(3, 'Enfermería'), (3, 'Estomatología'), (3, 'Medicina'), (3, 'Nutrición'), (3, 'Psicología'),
(3, 'Tecnología Médica'), (3, 'Administración de Empresas'), (3, 'Administración en Turismo y Hotelería'),
(3, 'Administración y Gestión Pública'), (3, 'Administración y Marketing'),
(3, 'Administración y Negocios Internacionales'), (3, 'Contabilidad'), (3, 'Economía'),
(3, 'Derecho'), (3, 'Ciencias de la Comunicación'), (3, 'Arte & Diseño Gráfico Empresarial'),
(3, 'Ciencias del Deporte'), (3, 'Educación Inicial'), (3, 'Educación Primaria'),
(3, 'Traducción e Interpretación'), (3, 'Arquitectura'), (3, 'Ingeniería Empresarial'),
(3, 'Ingeniería Agroindustrial'), (3, 'Ingeniería Ambiental'), (3, 'Ingeniería Civil'),
(3, 'Ingeniería de Minas'), (3, 'Ingeniería de Sistemas'), (3, 'Ingeniería Industrial'),
(3, 'Ingeniería Mecánica Eléctrica'), (3, 'Ingeniería en Ciencia de Datos'),
(3, 'Ingeniería en Ciberseguridad');

-- Insert Careers for UPN (id: 4)
INSERT INTO carrera (id_universidad, nombre) VALUES
(4, 'Administración'), (4, 'Administración Bancaria y Financiera'), (4, 'Administración y Gestión Empresarial'),
(4, 'Administración y Marketing'), (4, 'Administración y Negocios Internacionales'),
(4, 'Administración y Servicios Turísticos'), (4, 'Arquitectura y Diseño de Interiores'),
(4, 'Arquitectura y Urbanismo'), (4, 'Comunicación'), (4, 'Comunicación Audiovisual'),
(4, 'Comunicación y Diseño Gráfico'), (4, 'Comunicación y Marketing Digital'),
(4, 'Comunicación y Periodismo'), (4, 'Comunicación y Publicidad'), (4, 'Contabilidad y Finanzas'),
(4, 'Derecho'), (4, 'Diseño Industrial'), (4, 'Economía'), (4, 'Economía y Negocios Internacionales'),
(4, 'Enfermería'), (4, 'Farmacia y Bioquímica'), (4, 'Gastronomía y Gestión de Restaurantes'),
(4, 'Ingeniería Agroindustrial'), (4, 'Ingeniería Ambiental'), (4, 'Ingeniería Biomédica'),
(4, 'Ingeniería Civil'), (4, 'Ingeniería de Minas'), (4, 'Ingeniería de Sistemas Computacionales'),
(4, 'Ingeniería de Software'), (4, 'Ingeniería Electrónica'), (4, 'Ingeniería Empresarial'),
(4, 'Ingeniería en Ciencia de Datos'), (4, 'Ingeniería Geológica'), (4, 'Ingeniería Industrial'),
(4, 'Ingeniería Mecatrónica'), (4, 'Marketing Internacional'), (4, 'Medicina Humana'),
(4, 'Negocios Internacionales'), (4, 'Nutrición y Dietética'), (4, 'Obstetricia'),
(4, 'Psicología'), (4, 'Terapia Física y Rehabilitación');

-- Insert Careers for USMP (id: 5)
INSERT INTO carrera (id_universidad, nombre) VALUES
(5, 'Administración'), (5, 'Administración de Negocios Internacionales'), (5, 'Gestión de Recursos Humanos'),
(5, 'Marketing'), (5, 'Economía'), (5, 'Contabilidad y Finanzas'), (5, 'Arquitectura'),
(5, 'Ingeniería Civil'), (5, 'Ingeniería Industrial'), (5, 'Ingeniería de Computación y Sistemas'),
(5, 'Ciencias Aeronáuticas'), (5, 'Ingeniería en Ciencias de Datos'), (5, 'Ingeniería en Inteligencia Artificial'),
(5, 'Ingeniería en Ciberseguridad'), (5, 'Ciencias de la Comunicación'), (5, 'Turismo y Hotelería'),
(5, 'Psicología'), (5, 'Enfermería'), (5, 'Obstetricia'), (5, 'Medicina Humana'),
(5, 'Odontología'), (5, 'Derecho'), (5, 'Educación');

-- Insert Careers for UTP (id: 6)
INSERT INTO carrera (id_universidad, nombre) VALUES
(6, 'Administración de Empresas'), (6, 'Administración y Marketing'), (6, 'Administración de Negocios Internacionales'),
(6, 'Contabilidad'), (6, 'Derecho'), (6, 'Psicología'), (6, 'Ingeniería de Sistemas e Informática'),
(6, 'Ingeniería Civil'), (6, 'Ingeniería Industrial'), (6, 'Arquitectura'),
(6, 'Enfermería'), (6, 'Nutrición');

-- =================================================================
-- 3. Index Creation
-- =================================================================

-- Indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_viaje_fecha ON viaje(fecha_hora);
CREATE INDEX IF NOT EXISTS idx_viaje_estado ON viaje(estado);
CREATE INDEX IF NOT EXISTS idx_usuario_correo ON usuario(correo);
CREATE INDEX IF NOT EXISTS idx_reserva_pasajero ON reserva(id_pasajero);
CREATE INDEX IF NOT EXISTS idx_viaje_search ON viaje(estado, fecha_hora, origen);
CREATE INDEX IF NOT EXISTS idx_usuario_rating ON usuario(calificacion_promedio DESC);

-- =================================================================
-- Final Message
-- =================================================================

-- Pring a success message to the console
SELECT '✅ UniHitch Database Schema and Seed Data Loaded Successfully!' as message;

